version: '3.8'
services:
  redis:
    image: redis
    container_name: weather-redis
    ports:
      - "6379:6379"
  app:
    build: .
    container_name: weather-api-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
